CREATE TRIGGER TRG_ADDSTOKLOG
ON COMPANY_PRODUCTDEALER
AFTER UPDATE
AS
BEGIN

DECLARE @PRODUCTID INT
DECLARE @INCREASE INT = 20
DECLARE @DATE DATETIME=GETDATE()



SELECT @PRODUCTID=PRODUCTID FROM COMPANY_PRODUCTDEALER WHERE STOCKPIECE<2 AND PRODUCTID=@PRODUCTID


IF @PRODUCTID IS NOT NULL

BEGIN
INSERT INTO [dbo].[COMPANY_STOCKLOG]
           ([DATE_]
           ,[INCREASE]
           ,[PRODUCTID])
     VALUES
           (@DATE
           ,@INCREASE
           ,@PRODUCTID
	)
END


END

