--categoryname='ütü' olan ürünlerin listesi
CREATE VIEW V_PRODUCTLIST
AS
SELECT PC.CATEGORYNAME, P.PRODUCTCODE, P.PRODUCTNAME, P.UNITPRICE FROM PRODUCT_PRODUCT P
	INNER JOIN PRODUCT_PRODUCTCATEGORIES PC ON PC.ID=P.CATEGORYID
	WHERE PC.CATEGORYNAME LIKE '%Ütü%'
