--BAYİLERDEKİ TOPLAM STOK ADETLERİ

CREATE VIEW V_DEALERTOTALPRODUCTSTOCKPIECE
AS
SELECT D.DEALERNAME, SUM(STOCKPIECE) TOTALSTOCKPIECE FROM COMPANY_PRODUCTDEALER CP
	INNER JOIN COMPANY_DEALERS D ON D.ID=CP.DEALERID
	INNER JOIN PRODUCT_PRODUCT P ON P.ID=CP.PRODUCTID
	GROUP BY CP.DEALERID, D.DEALERNAME, P.PRODUCTNAME
	HAVING SUM(STOCKPIECE) IS NOT NULL