--BAYİLERE GÖRE ÜRÜNLERİN STOK ADEDİ VE ÜRÜN ADI
CREATE VIEW V_DEALERTOTALSTOCKPIECE
AS
SELECT CP.DEALERID, D.DEALERNAME, SUM(STOCKPIECE) TOTALSTOCKPIECE, P.PRODUCTNAME FROM COMPANY_PRODUCTDEALER CP
	INNER JOIN COMPANY_DEALERS D ON D.ID=CP.DEALERID
	INNER JOIN PRODUCT_PRODUCT P ON P.ID=CP.PRODUCTID
	GROUP BY CP.DEALERID, D.DEALERNAME, P.PRODUCTNAME


--- EXECUTE

---SELECT * FROM V_DEALERTOTALSTOCKPIECE ORDER BY 1 
