--Hangi ilde kaç tane bayi var?

CREATE VIEW V_TOTALDEALER
AS
SELECT D.CITYID, C.CITYNAME, COUNT(D.CITYID) TOTAL_DEALER FROM COMPANY_DEALERS D
	INNER JOIN ADDRESS_CITIES C ON C.ID=D.CITYID
	GROUP BY D.CITYID, C.CITYNAME;
