--Hangi kategoride kaç ürün var?

CREATE VIEW V_TOTALPRODUCT
AS
SELECT PC.CATEGORYNAME, COUNT(*) TOTALPRODUCT FROM PRODUCT_PRODUCT P
	INNER JOIN PRODUCT_PRODUCTCATEGORIES PC ON PC.ID=P.CATEGORYID
	GROUP BY PC.CATEGORYNAME;
