--en fazla satılan ürünler

CREATE PROC P_MAXPRODUCT
AS 
BEGIN
SELECT  S.PRODUCTID, P.PRODUCTNAME, SUM(STOCKPIECE) STOCKPIECE FROM SALES_SALES S
INNER JOIN COMPANY_PRODUCTDEALER CP ON S.PRODUCTID=CP.PRODUCTID
INNER JOIN PRODUCT_PRODUCT P ON P.ID=S.ID
GROUP BY S.PRODUCTID, P.PRODUCTNAME

END