--GİRİLEN AD YADA SOYAD DEĞİŞKENİNE GÖRE MÜŞTERİNİN KAÇ ADET ADRESİ OLDUĞUNU VE ADRES BİLGİLERİNİ SORGULAMA


CREATE PROC P_SEARCHCUSTOMERADDRESS
@NAME NVARCHAR(50) NULL,
@SURNAME NVARCHAR(50) 
AS
BEGIN

SELECT C.FIRSTNAME + ' ' + C.LASTNAME, COUNT(*) FROM SALES_CUSTOMERS C
INNER JOIN ADDRESS_ADDRESS A ON C.ID=A.CUSTOMERID
WHERE FIRSTNAME LIKE @NAME OR LASTNAME LIKE @SURNAME
GROUP BY C.FIRSTNAME , C.LASTNAME
ORDER BY COUNT(*) ASC

END

EXEC DBO.P_SEARCHCUSTOMERADDRESS
@NAME = 'MERVE',
@SURNAME = ''

