-- GİRİLEN BAYİ NUMARASINA GÖRE BAYİDEKİ ÜRÜNLERİN İSİMLERİNİ VE STOK ADETLERİNİ GÖSTEREN PROCEDURE

CREATE PROC P_DEALERSTOKPIECE
@DEALERID INT
AS
BEGIN
SELECT CD.DEALERNAME, P.PRODUCTCODE, P.PRODUCTNAME, SUM(CP.STOCKPIECE) TOTALSTOCKPIECE FROM COMPANY_PRODUCTDEALER CP
	INNER JOIN PRODUCT_PRODUCT P ON P.ID=CP.PRODUCTID
	INNER JOIN COMPANY_DEALERS CD ON CD.ID=CP.DEALERID
	WHERE CP.DEALERID=@DEALERID
	AND ( P.PRODUCTNAME IS NOT NULL OR P.PRODUCTCODE IS NOT NULL)
	GROUP BY CD.DEALERNAME, P.PRODUCTCODE, P.PRODUCTNAME

END

	