DECLARE @i INT=1000
DECLARE @CITYID TINYINT
DECLARE @CITYNAME NVARCHAR(30)
DECLARE @TOWNID SMALLINT
DECLARE @TOWNNAME NVARCHAR(50)
DECLARE @SERVICENAME NVARCHAR(100)
DECLARE @ADDRESSTEXT NVARCHAR(500)
DECLARE @NEIGBORHOOD VARCHAR(100)
DECLARE @PHONENUMBER1 CHAR(11) ='444 6 333'
DECLARE @NUMBER INT


while @i>0
BEGIN
SELECT TOP 1 @CITYID=ID, @CITYNAME=CITYNAME FROM [ADDRESS_CITIES] ORDER BY NEWID()
SELECT  @CITYID, @CITYNAME
SELECT TOP 1 @TOWNID=ID, @CITYID=CITYID, @TOWNNAME=TOWNNAME FROM [ADDRESS_TOWNS] WHERE @CITYID=CITYID ORDER BY NEWID()
SELECT  @TOWNID, @CITYID, @TOWNNAME

SET @SERVICENAME = CONCAT('BOSH ',@TOWNNAME+ ' Yetkili Servisi, '+@CITYNAME)
select @SERVICENAME

SELECT TOP 1 @NEIGBORHOOD=Mahalle FROM [Mahalle] ORDER BY NEWID()
SELECT @NEIGBORHOOD

SET @NUMBER=CONVERT(INT, RAND()*20+50)
select @NUMBER

--select @ADDRESSTEXT = CONCAT_WS(' ', trim(@DISTRICT),  'No:' , @NUMBER, @POSTALCODE, @TOWNNAME,'/',@CITYNAME )

SET @ADDRESSTEXT = CONCAT(TRIM(@NEIGBORHOOD)  , ' NO: ' , @NUMBER)
select @ADDRESSTEXT



INSERT INTO [dbo].[COMPANY_AUTHORIZEDSERVICE]
           ([CITYID]
           ,[TOWNID]
           ,[SERVICENAME]
           ,[ADDRESSTEXT]
           ,[PHONENUMBER1])
     VALUES
           (@CITYID
           ,@TOWNID
           ,@SERVICENAME
           ,@ADDRESSTEXT
           ,@PHONENUMBER1
           )

set @i=@i-1
END

